language: python
cache:
  - pip
  - npm
python:
  - "2.7"
node_js:
  - "4.4"
# install and run ERP app
before_install:
  - cd modules/erp
  - npm install
  - nohup bash -c "npm start" &
  - cd ../..
# command to install dependencies
install: "pip install -r requirements.dev.txt"
# command to run tests
before_script:
  - rm .env.local
  - source .env
script: python server/tests/run_tests.py